from pydantic import BaseModel, Field

# Define the response model for the upload endpoint
class UploadResponse(BaseModel):
    message: str
    session_id: str

# Define the request model for the chat endpoint
class chatrequest(BaseModel):
    """Request model for chat endpoint containing user query and session ID.
    Attributes:
        query (dict): The user query and optional image in base64 format.
        session_id (str): The current chat session ID.
    """
    query: dict 
    session_id: str

# Define the response model for the chat endpoint
class ChatResponse(BaseModel):
    """Response model for chat endpoint containing chat history and response.
    Attributes:
        chat_history (list): List of chat messages in the session.
        response (str): Response generated by the RAG chat system.
    """
    chat_history: list = Field(..., description="List of chat messages in the session",
                               example=[
                                  {"role": "user", "content": "What is the capital of France?"},
                                  {"role": "assistant", "content": "The capital of France is Paris."}
                              ])
    response: str = Field(..., description="Response generated by the RAG chat system",
                          example="The capital of France is Paris.")